version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Propix@123
      MYSQL_DATABASE: medicodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - C:/Users/scpt454/source/repos/data:/var/lib/mysql
    networks:
      - mysqlnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - mysqlnet

  webapi:
    image: sonali334/medicoapi:latest
    build:
      context: .
      dockerfile: Dockerfile    
    ports: 
      - "5002:8080"
    depends_on: 
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=medicodb;User=admin;Password=adminpassword;"
    networks:
      - mysqlnet

networks:
  mysqlnet:
