name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement
  pull_request:
    branches:
      - main  # Adjust if you need to trigger the workflow for PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET and build the application
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Adjust according to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      # Publish the app for deployment and upload the artifact
      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish  # Upload the 'publish' directory

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy only runs after build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: ./publish  # Path to download the 'publish' artifact

      - name: Add SSH host to known hosts
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory if it does not exist
          ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts  # Add the server's SSH key to known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set proper permissions for known_hosts file

      - name: Deploy to server
        env:
          HOST: 65.0.21.113  # Replace with your server's IP or hostname
          USER: ubuntu  # Replace with your SSH user
          PRIVATE_KEY: ${{ secrets.MEDICO_KEY }}  # Secret storing your private SSH key
        run: |
          echo "$PRIVATE_KEY" > private_key.pem  # Write the private key to a file
          chmod 600 private_key.pem  # Set permissions on the private key
          scp -i private_key.pem -r ./publish $USER@$HOST:/home/ubuntu/api-deploy/  # SCP the published files to the server
          ssh -i private_key.pem $USER@$HOST << EOF  # SSH into the server to restart the service
            cd /home/ubuntu/api-deploy
            sudo systemctl restart kestrel-api  # Restart the Kestrel API service
          EOF
