name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement
  pull_request:
    branches:
      - main  # Adjust if you need to trigger the workflow for PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for build, such as installing dependencies, restoring, building, etc.
      # Example: Install dependencies, build the app
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Adjust according to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      # Optionally, add test steps
      - name: Run tests
        run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download publish folder
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: ./publish

      - name: Add SSH host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          HOST: 65.0.21.113
          USER: ubuntu
          PRIVATE_KEY: ${{ secrets.MEDICO_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r ./publish $USER@$HOST:/home/ubuntu/api-deploy/
          ssh -i private_key.pem $USER@$HOST << EOF
            cd /home/ubuntu/api-deploy
            sudo systemctl restart kestrel-api
          EOF
