name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: ./publish

      - name: Add SSH host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa 65.0.21.113 >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | base64 -d > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private_key.pem

      - name: Deploy to EC2 instance
        env:
          HOST: 65.0.21.113
          USER: ubuntu
          PRIVATE_KEY: ${{ secrets.MEDICO_KEY }}
        run: |
          # Copy files to server
          scp -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no -r ./publish $USER@$HOST:/home/ubuntu/api-deploy/

          # SSH into server and restart the service
          ssh -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/ubuntu/api-deploy
            sudo systemctl restart kestrel-api
          EOF
          
      - name: Clean up
        run: |
          rm -rf ./publish
