name: .NET API CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test

    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload publish folder
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download publish folder
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: ./publish

    - name: Deploy to server
      env:
        HOST: 65.0.21.113
        USER: ubuntu
        PRIVATE_KEY: ${{ secrets.MEDICO_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r ./publish $USER@$HOST:/home/ubuntu/api-deploy/
        ssh -i private_key.pem $USER@$HOST << EOF
          cd /home/ubuntu/api-deploy
          sudo systemctl restart kestrel-api
        EOF
